title: Chuer Yang
description: Personal website for thoughts, projects, and curiosities
baseurl: "/chuer"       
url: "https://chuery.github.io"  

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: pretty

collections:
  travels:
    output: true
    permalink: /wanderings/:name/
